# Copyright 2026 Tulip Labs
# SPDX-License-Identifier: Apache-2.0

"""Filesystem-as-memory tool factory.

:func:`make_filesystem_tools` returns six ``@tool``-decorated ops
matching deepagents' filesystem catalogue: ``write_file``,
``read_file``, ``ls``, ``edit_file``, ``glob``, ``grep``. Each tool's
parameter schema is generated by tulip's ``@tool`` decorator from the
typed function signature, so the LLM sees clean flat fields.

Each tool catches :class:`BackendError` and returns the standardized
error code as its string output (``"file_not_found"``,
``"permission_denied"``, ``"is_directory"``, ``"invalid_path"``).
``edit_file`` separately surfaces a ``ValueError`` for the
unique-match contract violation.

The factory accepts any :class:`BackendProtocol` — :class:`StateBackend`
for in-memory ephemeral, :class:`FilesystemBackend` for rooted on-disk,
or any caller-supplied implementation (object storage, sandbox, …).
"""

from __future__ import annotations

import json
from dataclasses import asdict
from typing import Any

from tulip.deepagent.backends.protocol import (
    BackendError,
    BackendProtocol,
)
from tulip.tools.decorator import tool


def make_filesystem_tools(backend: BackendProtocol) -> list[Any]:
    """Build the six filesystem-as-memory tools bound to ``backend``.

    Returns:
        list of tulip ``Tool`` instances ready to splice into an
        ``Agent``'s ``tools=[...]`` argument.
    """

    @tool
    def write_file(path: str, contents: str) -> str:
        """Write ``contents`` to ``path``, creating or overwriting the
        file. Parent directories are created implicitly. Returns the
        path on success, or a standardized error code on failure
        (``"is_directory"``, ``"permission_denied"``, ``"invalid_path"``).
        """
        from tulip.observability.emit import EV_DEEPAGENT_FS_WRITE, emit_sync

        try:
            backend.write(path, contents)
        except BackendError as exc:
            return exc.code
        emit_sync(EV_DEEPAGENT_FS_WRITE, path=path, byte_count=len(contents))
        return path

    @tool
    def read_file(path: str, offset: int = 0, limit: int = 100) -> str:
        """Read up to ``limit`` lines from ``path`` starting at the
        0-indexed line ``offset``. Output is line-numbered (1-based,
        ``cat -n`` style). Default ``limit=100`` to avoid blowing the
        token budget on large files; raise it explicitly when needed.

        Returns the file content slice or a standardized error code
        (``"file_not_found"``, ``"is_directory"``,
        ``"permission_denied"``, ``"invalid_path"``).
        """
        from tulip.observability.emit import EV_DEEPAGENT_FS_READ, emit_sync

        try:
            content = backend.read(path, offset=offset, limit=limit)
        except BackendError as exc:
            return exc.code
        emit_sync(EV_DEEPAGENT_FS_READ, path=path, byte_count=len(content))
        return content

    @tool
    def ls(path: str = "/", recursive: bool = False) -> str:
        """List entries under ``path``. Set ``recursive=True`` to walk
        the entire subtree. Returns a JSON-encoded list of
        ``{path, is_dir, size, modified_at}`` records, or a
        standardized error code on failure.
        """
        try:
            entries = backend.ls(path, recursive=recursive)
        except BackendError as exc:
            return exc.code
        return json.dumps(
            [
                {
                    "path": fi.path,
                    "is_dir": fi.is_dir,
                    "size": fi.size,
                    "modified_at": fi.modified_at.isoformat() if fi.modified_at else None,
                }
                for fi in entries
            ]
        )

    @tool
    def edit_file(path: str, old_str: str, new_str: str) -> str:
        """Replace exactly one occurrence of ``old_str`` with ``new_str``
        in ``path``. The match must be unique — supply a longer or more
        specific snippet if the same substring appears multiple times.

        Returns the path on success, the standardized error code on
        backend failure, or a human-readable message describing the
        zero/multi-match condition (so the agent can retry with a
        better snippet).
        """
        try:
            backend.edit(path, old_str, new_str)
        except BackendError as exc:
            return exc.code
        except ValueError as exc:
            return str(exc)
        return path

    @tool
    def glob(pattern: str, path: str = "/") -> str:
        """POSIX-glob match files under ``path`` against ``pattern``
        (e.g. ``"**/*.md"`` or ``"notes-*.txt"``). Returns a
        JSON-encoded list of ``FileInfo`` records. Soft-bounded at 20
        seconds (the contract surface — the in-memory backend resolves
        instantly; on-disk backends terminate within budget).
        """
        try:
            entries = backend.glob(pattern, path=path, timeout_s=20.0)
        except BackendError as exc:
            return exc.code
        return json.dumps(
            [
                {
                    "path": fi.path,
                    "is_dir": fi.is_dir,
                    "size": fi.size,
                    "modified_at": fi.modified_at.isoformat() if fi.modified_at else None,
                }
                for fi in entries
            ]
        )

    @tool
    def grep(pattern: str, path: str = "/", recursive: bool = True) -> str:
        """Regex-search file contents under ``path``. Returns a
        JSON-encoded list of ``{path, line, text}`` matches with
        1-based line numbers. ``recursive=True`` (default) walks
        nested directories.
        """
        try:
            matches = backend.grep(pattern, path=path, recursive=recursive)
        except BackendError as exc:
            return exc.code
        return json.dumps([asdict(m) for m in matches])

    return [write_file, read_file, ls, edit_file, glob, grep]
